### ISSUE TITLE
Start mocking out HUB api on apiary.io

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1077]
### mvp

User
```yaml
# User ID
id: 5

# Date created and modified
created: 1253537353
modified: 1253537354

# Subscription level ID

# Email/pass
email: jeanluc@picard.io
password: ****

# Name stuff
first_name: Jean Luc
last_name: Picard
full_name: Jean Luc Picard

# Organziation ID 
organization: 1701 (Enterprise D)

# Amount of activity on the HUB?
activity: 97343
```

App 
```yaml
# App id
id: 4

# Meta
name: myapp
type: drupal7

# App config (would differ per app but here are some examples of the kind of stuff)
config: 
  custom_compose_yaml: { FILE CONTENTS }
  php_version: 55
  services:
    web: nginx:1.47
    db: mariadb:5.5
    index: solr:4.3

# Array of pull objects
pull: 
  - id: 3
    type: code
    location: girUrl
    branch: master
  - id: 6
    type: sql
    location: sqlArchive
    auth: token? user/pass?
  - id: 9
    type: files
    location: filesArchive
    auth: token? user/pass?
# Push array (allow DB and files at some point?)
push: 
  - id: 3
    type: code
    location: girUrl
    branch: dev

# People info
owner: 235 (jean luc picard)
created_by: 323 (jean luc picard)
created: 9273049723072
modified: 02307235

# Array of users who have access to this app
team: 
  - 6 (william t riker)
  - 3 (data)
  - 23 (dr beverly crusher)
```

Plans
```
id: 3
short: pro
long: Professional
cost: 
```

### Nice to have

Organizations
