### ISSUE TITLE
Services plugin does not seem to allow multiple domains/subdomains to map to the same service

### ISSUE THREAD

**Issue by baroneddy** [kalabox/kalabox#1182]
I am currently trying Kalabox and one of the first thing I need to setup is Domain Access on D7. I honestly have no idea how to configure my httpd.conf (or equivalent) on Kalabox :( Is it even possible?

Thanks for the help!

Ed

**Comment by pirog** [comment]
Are you using a stock drupal app or a pantheon one?

**Comment by baroneddy** [comment]
I installed D7 from Kalabox GUI without syncing anything with Pantheon yet.

**Comment by pirog** [comment]
hey @baroneddy this is not officially supported on our drupal apps at this point but i *think* you can probably do what you need to do using the kalabox services plugin. See https://kalabox.freshdesk.com/solution/articles/14000005137-core-plugins

I think you can probably edit your `kalabox.yml` file to something like this and do a `kbox restart` for the changes to take effect. If this throws an error let me know because i haven't actually tried this yet.


```yaml
name: backdrop
type: php
plugins:
  - kalabox-plugin-php
pluginconfig:
  cli: 'on'
  sharing:
    share: 'data:/var/www/html'
    ignore:
      - '!*modules*'
      - sites/default/files
      - files
      - wp-content/uploads
  services:
    appserver:
      - port: 80/tcp
        default: true
    appserver:
      - port: 80/tcp
        hostname: YOURSUBDOMAINHERE (just the web part of web.site.com)
  php:
    framework: backdrop
    version: '1'
    image: 'kalabox/backdrop:1'
version: v0.12

```

**Comment by baroneddy** [comment]
Thanks for your answer!

I add this to my service file:
`appserver:
      - port: 80/tcp
        hostname: test1`
Then `kbox restart`, but didn't work :( 

My main domain si test.kbox, subdomain is test1.test.kbox.
Thanks for you help!

**Comment by pirog** [comment]
Can you access the subdomain in the browser?

**Comment by baroneddy** [comment]
I can't :( Kalabox is telling me that there is nothing at this address.

But I had another weird problem, I re-launched Kalabox yesterday, and I lost the site I created the other day. Not cool :s I will open another issue if I can reproduce it.

**Comment by pirog** [comment]
@baroneddy yeah it's possible you can't have two address on the same service. I'll try to look into this at some point. 

Re: "losing" your site. This *definitely* should not be happening. I would open another issue and describe in a little more detail what you mean exactly by "losing" a site? There is nowhere in the Kalabox code where we purposefully delete a site or its containers without the user's OK so i'm very skeptical of this. It's possible that its just not showing up in teh GUI anymore but very unlikely that the site is "lost". 

That said, Kalabox **is still in alpha**.
https://kalabox.freshdesk.com/solution/articles/14000011858-kalabox-is-currently-in-alpha-does-that-mean-it-s-stable-

**Comment by dalin-** [comment]
@pirog Is there a syntax problem in your example?  Should we really be duplicating the `appserver` entry?

Also your `services` section looks significantly different from mine (maybe because the app I'm working with is on Pantheon):

```yml
  services:
    appserver:
      - port: 8888/tcp
        default: true
      - port: 444/tcp
        default: true
        secure: true
    edge:
      - port: 80/tcp
        hostname: edge
      - port: 443/tcp
        hostname: edge
        secure: true
```
Also, when I make a change do I need to restart all of Kalabox, or just the app that I'm working with?  

I'd love to get this working as most of the sites that I work with use either Organic Groups or Domain module to have subdomains.
