### ISSUE TITLE
Cannot read property 'git_url' of undefined at kalabox-plugin-pantheon/lib/pull.js:106 (Site add form is filled out)

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1318]
Bug Report
==========

**Tell us about your setup**

v0.12.0-alpha4 on MacOSX

Note that this error happened on alpha3, but was caused by a different error: see #1262 for information and *make sure to update to the latest Kalabox before commenting here.*

**Tell us about your bug**

On the initial site create you will get `Cannot read property 'git_url' of undefined at kalabox-plugin-pantheon/lib/pull.js:106` if you are doing a `kbox pull` you will get something like `Error: Cannot read property 'id' of undefined`. 

The issue here seems to be that the terminus container is not getting the correct user session. You can replicate this manually (if your apps are working correctly) by going into an existing app that works and

1. commenting out `- $KALABOX_ENGINE_HOME/.kalabox/pantheon/session/$KALABOX_APP_PANTHEON_CONFIG_EMAIL:/home/$KALABOX_ENGINE_ID/.terminus/cache/session` in `kalabox-cli.yml
2. Running `kbox pull`
3. Should produce  `Error: Cannot read property 'id' of undefined`

The reason why this happens for some people remains a mystery however. That said there are a few possible things to look at

1. Is your `pantheon email` set correctly in the `kalabox.yml` file in your app's root directory.
2. Do you have a session file at `~/.kalabox/pantheon/session/YOUR_PANTHEON_ACCOUNT_EMAIL`
3. From inside your app run `kbox env | grep YOUR_PANTHEON_ACCOUNT_EMAIL`

**Tell us more**

This bug will prevent people from using Kalabox.

**Notes**

There is a very strong chance we could avoid this by addressing #905

**Comment by rovo79** [comment]
I'm receiving the same error.

**Comment by reynoldsalec** [comment]
@rovo79 can you confirm that you are using Alpha4 and that the form issue detailed in #1262 is not the problem?

**Comment by pirog** [comment]
We have been unable to create this issue but here are some steps to upgrade the terminus version in your app to see if that resolves the issue.

#### Go to the app directory that is failing 
`cd /path/to/app`

#### Switch the terminus image to build from a local dockerfile

Use the text editor of your choice, scroll down to the terminus section and make sure the top few lines of that section look like this. You will basically be swapping the comment/uncomment from the `image` and `build` keys.

```yaml
# Pantheon tooling.
#
# This contains additional Pantheon specific tooling options such as
# drush, wp-cli and terminus.
#
terminus:

  # Comment this and uncomment 'build' below if you want to edit your
  # local dockerfile and build from there. This is useful for development
  # image: kalabox/terminus:$KALABOX_APP_PANTHEON_CONFIG_IMAGES

  # Uncomment this and comment 'image' above if you want to edit your
  # local dockerfile and build from there. This is useful for development
  #
  build: ./dockerfiles/terminus

```

#### Edit the terminus dockerfile to upgrade 

From the app root open up `dockerfiles/terminus/Dockerfile`. Look for the following line

`curl https://github.com/pantheon-systems/cli/releases/download/0.10.6/terminus.phar -L -o /usr/local/bin/terminus && \`

And replace it with 

`curl https://github.com/pantheon-systems/terminus/releases/download/0.11.1/terminus.phar -L -o /usr/local/bin/terminus && \`

#### Rebuild your images

```bash
cd /path/to/app
kbox rebuild -- -v
```

#### Attempt to make pull great again

```
kbox pull
```

Let us know if that changes anything!
