### ISSUE TITLE
Define custom URL for kbox routing

### ISSUE THREAD

**Issue by andrewmallis** [kalabox/kalabox#1485]
I am trying to test some redirects in settings.php
I would like to edit my `/etc/hosts` file to point the live client site to a local IP.
I would like kalabox to accept requests to this URL.

Not presuming an implementation like this would work, but in sprit maybe something like this in ``klabox.yml``:

```
    web:
      - port: 8888/tcp
        default: true
      - port: 444/tcp
        default: true
        secure: true
        url: www.mydomain.com
```
