### ISSUE TITLE
Kalabox fails to pull app from Pantheon when framework is not set. Drupal 6 only?

### ISSUE THREAD

**Issue by ioskevich** [kalabox/kalabox#1608]
Kalabox 2.0, OsX El Capitan and MacOS Sierra

When pulling app from Pantheon, I am getting the error: 

> YAMLException: unacceptable kind of an object to dump [object Undefined]

Site is Drupal6, has rather large DB (4GB+).

After the error is fired, Kalabox GUI is just showing the App in "Creating" status:

<img width="692" alt="kalabox_and_new_issue_ _kalabox_kalabox" src="https://cloud.githubusercontent.com/assets/1148620/18723857/ffe66798-8042-11e6-92fa-8816bafb22b3.png">

**Comment by pirog** [comment]
@ioskevich does this just happen for your drupal6 site? i know that @labboy0276 has been running D6 sites successfully.

**Comment by ioskevich** [comment]
@pirog To be exact, this happens for this one particular Drupal 6 site so far (didin't try with other D6 yet since there was no need to pull them locally). I believe, there is a chance there is some site's config that prevents Kalabox from pulling it (the site itself is quite old and complex with various generations of developers worked on it previously), but looking through logs I couldn't find the reason. Error itself is fired in /Applications/Kalabox.app/Contents/Resources/app.nw/node_modules/js-yaml/lib/js-yaml/dumper.js, but my programming skills seems are not enough to understand what exactly caused it.

**Comment by pirog** [comment]
@ioskevich yeah that error you are getting seems to happen right when kalabox is generating the config file for your app. after it fails have you looked at the failed app folder and checked out the kalabox.yml file?

**Comment by ioskevich** [comment]
Well, the file is there (attached) but I am not sure what to look at. It seems incomplete, I would expect more services definitions there :)

[kalabox.txt](https://github.com/kalabox/kalabox/files/487581/kalabox.txt)

**Comment by pirog** [comment]
yeah this should look something like

```yml
name: seven
type: pantheon
plugins:
  - kalabox-plugin-pantheon
pluginconfig:
  cli: 'on'
  sharing:
    share: 'data:/code'
    ignore:
      - Name sites/default/files
  services:
    web:
      - port: 8888/tcp
        default: true
      - port: 444/tcp
        default: true
        secure: true
    edge:
      - port: 80/tcp
        hostname: edge
      - port: 443/tcp
        hostname: edge
        secure: true
  pantheon:
    site: kalabox-drupal7
    env: dev
    uuid: ID
    framework: drupal
    upstream:
      url: 'git://github.com/pantheon-systems/drops-7.git'
      product_id: 21e1fada-199c-492b-97bd-0b36b53a9da0
      branch: master
    images: v2.0.0
    php: 55
    name: Mike Pirog
    email: mike@things.io
version: 2.0.0
```

So it seems like there is something weird in the config we are getting from pantheon. I would check the runtime logs (see doc link above), i *think* they detail the results we get from pantheon.
