### ISSUE TITLE
drush commands are producing errors in Drupal 7 using Kalabox CLI

### ISSUE THREAD

**Issue by edisch** [kalabox/kalabox#1750]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

v2.1.3 on macOS Sierra version 10.12.1

Have you previously installed Kalabox? If so, what version?

No.

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

I'm having issues with running drush commands in my Drupal 7 Kalabox environment. Other team members are having trouble with setting up their containers and are running into a similar issue with drush not working quite right. Below is a screenshot of the error when trying to run drush in a Kalabox environment.

![screen shot 2016-12-15 at 12 24 33 pm](https://cloud.githubusercontent.com/assets/1893118/21241034/84b61a04-c2d3-11e6-8df5-73aeb05afe54.png)

Please detail the steps we can take to replicate this bug. Be as detailed as possible. 

1. Set up a basic Drupal 7 instance using `kbox start` in a folder with the following kalabox related files:
- `kalabox-compose.yml`
```
#
# Kalabox Drupal compose file
#
# This contains the core service definitions to run Drupal on Kalabox. This
# is a docker-compose file so please check out the compose file documentation
# over at https://docs.docker.com/compose/compose-file/.
#
# There are, however, a few caveats to take into account kalabox-compose.ymls
#
#   1. It is probably a bad idea to use the `container_name` key.
#
#   2. You can run `kbox env` inside of your app for a list of environmental
#      variables that you can use inside of this compose file.
#
#   3. Ports need to be exposed to the host on the outside using
#
#      ports:
#       - "PORTNUMBER"
#
#      Otherwise they are not usable in the services plugin.
#
#    4. The config directory in your app root contains a lot of
#       service config that is shared into each service. This is all
#       editable directly and should take on a `kbox restart`.
#

#
# This defines a data container to share common drupal app assets such as:
#
#   1. /media - Static assets like images and compiled css, Your files/wp-uploads
#               directory is symlinked here
#
#   3. /var/lib/mysql - MariaDB databases to preserve data on rebuilds
#
#   4. /var/www/html - Your applications codebase, also where you shared code lives
#
data:

  # Comment this and uncomment 'build' below if you want to edit your
  # local dockerfile and build from there. This is useful for development
  image: busybox

  # Uncomment this and comment 'image' above if you want to edit your
  # local dockerfile and build from there. This is useful for development
  #
  # build: ./dockerfiles/data

  volumes:
    - /var/lib/mysql
    - /var/www/html
    - $KALABOX_APP_ROOT_BIND/files:/var/www/html/$KALABOX_APP_PHP_CONFIG_FILEMOUNT

#
# This defines a basic Drupal appserver.
#
# The $KALABOX_APP_DRUPAL_CONFIG_VERSION var should contain the
# appropriate major version of drupal
#
#
appserver:

  # Comment this and uncomment 'build' below if you want to edit your
  # local dockerfile and build from there. This is useful for development
  # image: $KALABOX_APP_PHP_CONFIG_IMAGE

  # Uncomment this and comment 'image' above if you want to edit your
  # local dockerfile and build from there. This is useful for development
  #
  build: ./dockerfiles/${KALABOX_APP_PHP_CONFIG_FRAMEWORK}${KALABOX_APP_PHP_CONFIG_VERSION}

  hostname: $KALABOX_APP_CONFIG_NAME.$KALABOX_APP_CONFIG_DOMAIN
  volumes:
    - $KALABOX_APP_ROOT_BIND/config/apache/apache2-foreground:/usr/local/bin/apache2-foreground
  environment:
    FRAMEWORK: $KALABOX_APP_PHP_CONFIG_FRAMEWORK
    KALABOX_UID: $KALABOX_ENGINE_ID
    KALABOX_GID: $KALABOX_ENGINE_GID
  volumes_from:
    - data
  links:
    - db:database
    - db:mysql
  ports:
    - "80"

#
# This defines a basic database server.
#
db:

  # Comment this and uncomment 'build' below if you want to edit your
  # local dockerfile and build from there. This is useful for development
  image: mysql

  # Uncomment this and comment 'image' above if you want to edit your
  # local dockerfile and build from there. This is useful for development
  #
  # build: ./dockerfiles/db

  volumes_from:
    - data
  ports:
    - "3306"
  environment:
    MYSQL_USER: $KALABOX_APP_PHP_CONFIG_FRAMEWORK
    MYSQL_PASSWORD: $KALABOX_APP_PHP_CONFIG_FRAMEWORK
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: $KALABOX_APP_PHP_CONFIG_FRAMEWORK

```
- `kalabox-cli.yml`
```
#
# This contains additional services needed by the cli plugin.
#

#
# Basic cli tooling.
#
# This is a small alpine linux container that contains some basic and common
# cli tools like git, rsync and bash.
#
# It shares your entire user directory in at /user.
#
cli:
  # Comment this and uncomment 'build' below if you want to edit your
  # local dockerfile and build from there. This is useful for development
  image: kalabox/cli:stable

  # Uncomment this and comment 'image' above if you want to edit your
  # local dockerfile and build from there. This is useful for development
  #
  # build: ./dockerfiles/cli

  volumes:
    - $KALABOX_ENGINE_HOME:/user
  volumes_from:
    - data
  environment:
    WEBROOT: /var/www/html
    TERM: xterm-color
    KALABOX_UID: $KALABOX_ENGINE_ID
    KALABOX_GID: $KALABOX_ENGINE_GID
    #GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentityFile=/user/.ssh/pantheon.kalabox.id_rsa
    #GIT_AUTHOR_NAME: $KALABOX_APP_PANTHEON_CONFIG_NAME
    #GIT_AUTHOR_EMAIL: $KALABOX_APP_PANTHEON_CONFIG_EMAIL
    #GIT_COMMITTER_NAME: $KALABOX_APP_PANTHEON_CONFIG_NAME
    #GIT_COMMITTER_EMAIL: $KALABOX_APP_PANTHEON_CONFIG_EMAIL
  links:
    - db:database
  working_dir: $KALABOX_CLI_WORKING_DIR
  stdin_open: true
  tty: true
```
- `kalabox.yml`
```
name: {my-kbox-name}
type: php
plugins:
  - kalabox-plugin-php
pluginconfig:
  cli: 'on'
  sharing:
    share: 'data:/var/www/html'
    codeDir: 'docroot'
    ignore:
      - Name sites/default/files
  services:
    appserver:
      - port: 80/tcp
        default: true
  php:
    framework: drupal
    version: '7'
    filemount: sites/default/files
    image: 'drupal:7'
version: 2.1.2
```
- `cli.yml`
```
#
# Cli plugin task definition
#
# If the cli plugin is enabled in kalabox.yml then this file will be
# used used to specify the tooling commands that this app can run.
#
# Each object defines a specific task. When a task is implemnented correctly
# it should show up when you run `kbox` inside of your app. T
#
# Tasks can use any of the services in kalabox-compose.yml, kalabox-cli.yml or
# other compose files you load with your app.
#
# Here is a general description of a task object
#
# commandname:
#
#   service: [service] - The service on which to run the command.
#
#   stripfirst: [true|false] - If your commandname key is different from the
#     entrypoint you might want to strip the commandname aka running `kgit git`
#     vs `kgit`.
#
#   entrypoint: [string|array] - The binary to use. This will default to the
#     entrypoint of the service.
#
#   description: [string] - A human readable description that will show up
#     on the CLI.
#
#   precmdopts: [string] - A string of options to insert between the entrypoint
#     and the command the user types.
#
#   postcmdopts: [string] - A string to append to the user entered command.
#
#   mapping: [string] - A string that maps an approot path to a path inside the container
#     so we can set a accurate working directory for our task. You can use <> notation to
#     map to other properties on the app object
#
#
# NOTE: You will want to make sure your services correctly set relevant options
# such as sharing config files or the working directory.
#

#
# Adds a git command to your Pantheon app.
#
# You can still use your local git if you want. We also use a git wrapper called
# `kgit` to handle sharing files correctly.
#
# By default your git commands will use your Pantheon ssh key and git user/email
# will be based on your Pantheon info.
#
# This will run relative to your webroot.
#
git:
  service: cli
  description: Run a git command on your codebase
  mapping: <config.sharing.codeDir>:/var/www/html

#
# Adds a rsync command to your Pantheon app.
#
# This will run relative to your files directory.
#
rsync:
  service: cli
  description: Run a rsync command on your files directory
  mapping: files:/media

#
# Adds a node command to your pantheon app.
#
# Commands will be run relative to your webroot.
#
node:
  service: cli
  description: Run a node command
  mapping: <config.sharing.codeDir>:/var/www/html

#
# Adds a npm command to your pantheon app.
#
# Commands will be run relative to your webroot.
#
npm:
  service: cli
  description: Run a npm command
  mapping: <config.sharing.codeDir>:/var/www/html

#
# Adds a grunt command to your pantheon app.
#
# Commands will be run relative to your webroot.
#
grunt:
  service: cli
  description: Run a grunt command
  mapping: <config.sharing.codeDir>:/var/www/html

#
# Adds a gulp command to your pantheon app.
#
# Commands will be run relative to your webroot.
#
gulp:
  service: cli
  description: Run a gulp command
  mapping: <config.sharing.codeDir>:/var/www/html

#
# Adds a bower command to your pantheon app.
#
# Commands will be run relative to your webroot.
#
bower:
  service: cli
  description: Run a bower command
  mapping: <config.sharing.codeDir>:/var/www/html
```
- `dockerfiles/drush/Dockerfile`
```
# Standard drush image

FROM drush/drush:8

# @todo: 8-php5

#
# Add your custom stuff here, you will want to make sure
# you switch from `image` to `build` mode in the relevant
# .yml compose file.
#
# For more information on dockerfiles see:
#
#   https://docs.docker.com/engine/reference/builder/
#
```
- `dockerfiles/drupal7/Dockerfile`
```
# Standard Drupal 7 image

FROM drupal:7

RUN apt-get update -y && apt-get install libxml2-dev -y && apt-get install php-soap -y && docker-php-ext-install soap

#
# Add your custom stuff here, you will want to make sure
# you switch from `image` to `build` mode in the relevant
# .yml compose file.
#
# For more information on dockerfiles see:
#
#   https://docs.docker.com/engine/reference/builder/
#

```
2. All appropriate containers we're instantiated
![screen shot 2016-12-15 at 2 48 03 pm](https://cloud.githubusercontent.com/assets/1893118/21242115/57ac9ba0-c2d8-11e6-9a8a-1875a040c244.png)

3. And then when running `kbox drush cc all` I get the following error
![screen shot 2016-12-15 at 12 24 33 pm](https://cloud.githubusercontent.com/assets/1893118/21241744/c6591558-c2d6-11e6-8270-1491ba6dfc80.png)

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
It would be awesome if there was more documentation on how to set up an acquia hosted site with Kalabox. We like Kalabox over Acquia Dev Desktop but can't get it working in this case.

Does this bug prevent you from using Kalabox?
_Yes, some of our team can't get set up due to this issue._
