### ISSUE TITLE
Create a way for the GUI to also package in external assets like VB installer, etc

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#378]
Use the current Travis build process to include dependencies like the boot2docker package (VirtualBox), syncthing, couple flat files.

**Comment by pirog** [comment]
you can probably grab a lot of the metadata for the things you need to DL ie URLS from the kalabox/kalabox-engine-docker source

**Comment by reynoldsalec** [comment]
Sweet, thanks for the tip on that @pirog , https://github.com/kalabox/kalabox-engine-docker/blob/master/lib/meta.js has most of what I require for success.

One question: I was thinking of setting up an additional Grunt tasks "grunt package" that would basically be the same as build, but will run an additional step to download dependencies. Travis will run that, but it'll allow us to build the entire package locally as well for testing/other nefarious purposes.

**Comment by pirog** [comment]
We need to figure out where these files would live on Win and Linux.  I *think* we can package and extract files out of an exe but im not sure what we need to do for a linux binary. we could just roll a .deb that puts the deps somewhere

**Comment by pirog** [comment]
so i think what we can do here is get the pkg assets into nw like any other file.

but i ​*think*​ we can package in like the boot2docker.pkg installer into nw

and then i ​*think*​ we can actually have context for that internally in node
i mean in nw
context ie the file location
cause that is how require would work
which means we probably can just copy it to a temp dir and run it from there

**Comment by pirog** [comment]
We also need to do some work re #380 to specify the download folder.

**Comment by pirog** [comment]
So i think the simplest thing here is to have a platform specific config file with our build deps and to have some sort of `grunt buildWithDeps` command. 

```yml
deps:
  - virtualBox.pkg
  - docker-machine
  - docker-compose
  - boot2docker.iso
  - syncthing
images:
  - kalabox/cli:v0.11.0
  - kalabox/dns:v0.11.0
  - kalabox/proxy:v0.11.0
  - kalabox/syncthing:v0.11.0
  - kalabox/pantheon-appserver:/v0.11.0
  - etc
```

1. It will go through and download all the deps and put them somewhere in the NW root. 
2. Then in our download method we can check if each of these files exist locally and if they do then we can stream in and stream out to ~/.kalabox/downloads.
3. Everything else should proceed normally
4. For the ISO image we just need to have a check for machine to look in ~/.kalabox/downloads first
5. How to handle images covered by #385
