### ISSUE TITLE
Create functional test YAML file format

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#755]
We should be able to provide a YAML file with the meta data on the kinds of test we will run. here is a first pass idea. 

```yaml

## List of projects
projects:
  core:
    # The git location of the core 
    git: https://github.com/kalabox/kalabox.git
    # what tag hash or branch to checkout
    commit: tag|hash|branch
    tests: 
    # Run all the tests inside a given plugin, or list the specific tests
    # in each plugin, or paths from the project root
      - kalabox_core: all  
      - kalabox_syncthing:
          - syncfiles.sh
          - ragetest.sh
      - kalabox_dev: none 
      - files: 
        - test/thing/test.js
  engine: 
    git: https://github.com/kalabox/kalabox-engine-docker.git
    commit: tag|hash|branch
    tests: 
      - files:
        - tests/install.sh
  services: 
    git: https://github.com/kalabox/kalabox-services-docker.git
    commit: tag|hash|branch
    tests: none 
  apps: 
    - git: https://github.com/kalabox/kalabox-app-pantheon.git
      commit: tag|hash|branch
# turn devMode on or off
dev_mode: true|false
# should be a list of VMWARE images|start states|exports?
run_on:
  - debian7
  - win7
  - win81
  - win10
  - fedora23
  - osx1011
# Build a binary after tests are done
build_binary: true|false
# Run all the tests again but use the binary
test_binary: true|false
```
