### ISSUE TITLE
0.11.0 Edge Containers causing some syncthing issues

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#858]
Hello!

The Edge / Varnish container seems to be causing some syncthing sadness.  Small changes may not get picked up sometimes, syncthing doesn't update sometimes, etc.  

Workaround it to edit the kalabox.yml as such:
```
services:
   appserver:
     - port: 8888/tcp
       default: true
       # hostname: appserver
   # edge:
   #   - port: 80/tcp
   #     default: true
   #   - port: 443/tcp
   #     default: true
   #     secure: true
```

Thoughts?
