### ISSUE TITLE
Redis Server Went Away?

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#917]
Hello!

Created an app and tried to clear cache (all drush commands produce this result as well) and I get the error below:

The app works in the browser,but it seems to think there is no redis server?  I made sure it was on PHP 5.3 for the site as I thought that what the error was, but it is all good on that front.

Thoughts?

```
john@kalamuna:~/kalabox/apps/prna/code$ kbox drush cc all
info: COMPOSE =>  0=--project-name, 1=prna, 2=--file, 3=/home/john/kalabox/apps/prna/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/prna/kalabox-cli.yml, 6=--file, 7=/home/john/kalabox/apps/prna/kalabox-cli.yml, 8=run, 9=--entrypoint, 10=bash --login -c, 11=--rm, 12=terminus, 13=drush8 cc all --strict=0, mode=attach
Starting prna_data_1
Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known PhpRedis.php:14                            [warning]
Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known PhpRedis.php:14                            [warning]
Drush command terminated abnormally due to an unrecoverable error.                                                                   [error]
<h1>Additional uncaught exception thrown while handling exception.</h1><h2>Original</h2><p>RedisException: Redis server went away in Redis-&gt;auth() (line 18 of /code/sites/all/modules/redis/lib/Redis/Client/PhpRedis.php).</p><h2>Additional</h2><p>RedisException: Redis server went away in Redis-&gt;auth() (line 18 of /code/sites/all/modules/redis/lib/Redis/Client/PhpRedis.php).</p><hr />info: DOCKER-COMPOSE =>  Run exited with code: 1
Unhandled rejection VError: code1err:more:
    at ChildProcess.<anonymous> (/usr/local/bin/lib/util/shell.js.jx:247:16)
    at ChildProcess.emit (events.js:85:9)
    at maybeClose (child_process.js:773:12)
    at Process.ChildProcess._handle.onexit (child_process.js:839:1)
From previous event:
    at Object.exports.spawn (/usr/local/bin/lib/util/shell.js.jx:211:10)
    at Object.sh (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/lib/bin.js.jx:92:20)
    at /usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:60:18
From previous event:
    at shCompose (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:42:6)
    at Object.run (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:343:12)
    at /usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:260:24
    at arrayMap (/usr/local/bin/node_modules/lodash/index.js.jx:1405:25)
    at Function.map (/usr/local/bin/node_modules/lodash/index.js.jx:6709:14)
    at Object.run (/usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:177:26)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:471:29
From previous event:
    at Object.exports.run (/usr/local/bin/lib/engine.js.jx:470:4)
    at Object.task.func (/usr/local/bin/plugins/kalabox-cli/lib/tasks.js.jx:100:34)
    at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:884:15)
    at processTask (/usr/local/bin/bin/kbox.js.jx:168:16)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:231:12)
    at process._tickCallback (node.js:803:1)
From previous event:
    at main (/usr/local/bin/bin/kbox.js.jx:230:4)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:239:1)
    at Module._compile (module.js:595:24)
    at readX (module.js:1488:3)
    at Object.Module._extensions..jx (module.js:1921:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (_jx_source:17:1)
    at Module._compile (module.js:595:24)
    at Module.load (module.js:425:6)
    at Function.Module._load (module.js:380:8)
    at Function.Module.runMain (module.js:813:8)
    at startup (node.js:374:8)
    at node.js:1461:1
```

**Comment by pirog** [comment]
I assume this only happens running drush and things are fine through the ui
on the appserver?

On Sunday, January 31, 2016, John Ouellet <notifications@github.com> wrote:

> Hello!
>
> Created an app and tried to clear cache (all drush commands produce this
> result as well) and I get the error below:
>
> The app works in the browser,but it seems to think there is no redis
> server? I made sure it was on PHP 5.3 for the site as I thought that what
> the error was, but it is all good on that front.
>
> Thoughts?
>
> john@kalamuna:~/kalabox/apps/prna/code$ kbox drush cc all
> info: COMPOSE =>  0=--project-name, 1=prna, 2=--file, 3=/home/john/kalabox/apps/prna/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/prna/kalabox-cli.yml, 6=--file, 7=/home/john/kalabox/apps/prna/kalabox-cli.yml, 8=run, 9=--entrypoint, 10=bash --login -c, 11=--rm, 12=terminus, 13=drush8 cc all --strict=0, mode=attach
> Starting prna_data_1
> Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known PhpRedis.php:14                            [warning]
> Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known PhpRedis.php:14                            [warning]
> Drush command terminated abnormally due to an unrecoverable error.                                                                   [error]
> <h1>Additional uncaught exception thrown while handling exception.</h1><h2>Original</h2><p>RedisException: Redis server went away in Redis-&gt;auth() (line 18 of /code/sites/all/modules/redis/lib/Redis/Client/PhpRedis.php).</p><h2>Additional</h2><p>RedisException: Redis server went away in Redis-&gt;auth() (line 18 of /code/sites/all/modules/redis/lib/Redis/Client/PhpRedis.php).</p><hr />info: DOCKER-COMPOSE =>  Run exited with code: 1
> Unhandled rejection VError: code1err:more:
>     at ChildProcess.<anonymous> (/usr/local/bin/lib/util/shell.js.jx:247:16)
>     at ChildProcess.emit (events.js:85:9)
>     at maybeClose (child_process.js:773:12)
>     at Process.ChildProcess._handle.onexit (child_process.js:839:1)
> From previous event:
>     at Object.exports.spawn (/usr/local/bin/lib/util/shell.js.jx:211:10)
>     at Object.sh (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/lib/bin.js.jx:92:20)
>     at /usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:60:18
> From previous event:
>     at shCompose (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:42:6)
>     at Object.run (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:343:12)
>     at /usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:260:24
>     at arrayMap (/usr/local/bin/node_modules/lodash/index.js.jx:1405:25)
>     at Function.map (/usr/local/bin/node_modules/lodash/index.js.jx:6709:14)
>     at Object.run (/usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:177:26)
> From previous event:
>     at /usr/local/bin/lib/engine.js.jx:471:29
> From previous event:
>     at Object.exports.run (/usr/local/bin/lib/engine.js.jx:470:4)
>     at Object.task.func (/usr/local/bin/plugins/kalabox-cli/lib/tasks.js.jx:100:34)
>     at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:884:15)
>     at processTask (/usr/local/bin/bin/kbox.js.jx:168:16)
>     at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:231:12)
>     at process._tickCallback (node.js:803:1)
> From previous event:
>     at main (/usr/local/bin/bin/kbox.js.jx:230:4)
>     at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:239:1)
>     at Module._compile (module.js:595:24)
>     at readX (module.js:1488:3)
>     at Object.Module._extensions..jx (module.js:1921:8)
>     at Module.load (module.js:416:30)
>     at Function.Module._load (module.js:380:8)
>     at Module.require (module.js:451:15)
>     at require (module.js:469:13)
>     at Object.<anonymous> (_jx_source:17:1)
>     at Module._compile (module.js:595:24)
>     at Module.load (module.js:425:6)
>     at Function.Module._load (module.js:380:8)
>     at Function.Module.runMain (module.js:813:8)
>     at startup (node.js:374:8)
>     at node.js:1461:1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/917>.
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc

**Comment by labboy0276** [comment]
correct

On Sun, Jan 31, 2016 at 1:27 PM, Mike Pirog <notifications@github.com>
wrote:

> I assume this only happens running drush and things are fine through the ui
> on the appserver?
>
> On Sunday, January 31, 2016, John Ouellet <notifications@github.com>
> wrote:
>
> > Hello!
> >
> > Created an app and tried to clear cache (all drush commands produce this
> > result as well) and I get the error below:
> >
> > The app works in the browser,but it seems to think there is no redis
> > server? I made sure it was on PHP 5.3 for the site as I thought that what
> > the error was, but it is all good on that front.
> >
> > Thoughts?
> >
> > john@kalamuna:~/kalabox/apps/prna/code$ kbox drush cc all
> > info: COMPOSE => 0=--project-name, 1=prna, 2=--file,
> 3=/home/john/kalabox/apps/prna/kalabox-compose.yml, 4=--file,
> 5=/home/john/kalabox/apps/prna/kalabox-cli.yml, 6=--file,
> 7=/home/john/kalabox/apps/prna/kalabox-cli.yml, 8=run, 9=--entrypoint,
> 10=bash --login -c, 11=--rm, 12=terminus, 13=drush8 cc all --strict=0,
> mode=attach
> > Starting prna_data_1
> > Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or
> service not known PhpRedis.php:14 [warning]
> > Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or
> service not known PhpRedis.php:14 [warning]
> > Drush command terminated abnormally due to an unrecoverable error.
> [error]
> > <h1>Additional uncaught exception thrown while handling
> exception.</h1><h2>Original</h2><p>RedisException: Redis server went away
> in Redis-&gt;auth() (line 18 of
> /code/sites/all/modules/redis/lib/Redis/Client/PhpRedis.php).</p><h2>Additional</h2><p>RedisException:
> Redis server went away in Redis-&gt;auth() (line 18 of
> /code/sites/all/modules/redis/lib/Redis/Client/PhpRedis.php).</p><hr
> />info: DOCKER-COMPOSE => Run exited with code: 1
> > Unhandled rejection VError: code1err:more:
> > at ChildProcess.<anonymous> (/usr/local/bin/lib/util/shell.js.jx:247:16)
> > at ChildProcess.emit (events.js:85:9)
> > at maybeClose (child_process.js:773:12)
> > at Process.ChildProcess._handle.onexit (child_process.js:839:1)
> > From previous event:
> > at Object.exports.spawn (/usr/local/bin/lib/util/shell.js.jx:211:10)
> > at Object.sh
> (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/lib/bin.js.jx:92:20)
> > at
> /usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:60:18
> > From previous event:
> > at shCompose
> (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:42:6)
> > at Object.run
> (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:343:12)
> > at /usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:260:24
> > at arrayMap (/usr/local/bin/node_modules/lodash/index.js.jx:1405:25)
> > at Function.map (/usr/local/bin/node_modules/lodash/index.js.jx:6709:14)
> > at Object.run
> (/usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:177:26)
> > From previous event:
> > at /usr/local/bin/lib/engine.js.jx:471:29
> > From previous event:
> > at Object.exports.run (/usr/local/bin/lib/engine.js.jx:470:4)
> > at Object.task.func
> (/usr/local/bin/plugins/kalabox-cli/lib/tasks.js.jx:100:34)
> > at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:884:15)
> > at processTask (/usr/local/bin/bin/kbox.js.jx:168:16)
> > at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:231:12)
> > at process._tickCallback (node.js:803:1)
> > From previous event:
> > at main (/usr/local/bin/bin/kbox.js.jx:230:4)
> > at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:239:1)
> > at Module._compile (module.js:595:24)
> > at readX (module.js:1488:3)
> > at Object.Module._extensions..jx (module.js:1921:8)
> > at Module.load (module.js:416:30)
> > at Function.Module._load (module.js:380:8)
> > at Module.require (module.js:451:15)
> > at require (module.js:469:13)
> > at Object.<anonymous> (_jx_source:17:1)
> > at Module._compile (module.js:595:24)
> > at Module.load (module.js:425:6)
> > at Function.Module._load (module.js:380:8)
> > at Function.Module.runMain (module.js:813:8)
> > at startup (node.js:374:8)
> > at node.js:1461:1
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kalabox/kalabox/issues/917>.
> >
>
>
> --
> Mike Pirog
> Co-Founder, Kalabox Inc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/917#issuecomment-177571227>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
In your Kalabox-CLI.yml make sure terminus also has links to the solr and
redis services. Use the appserver definition in Kalabox-compose as a
guide. Rebuild.

Does that fix it?

If so, submit a pr with the fix.

**Comment by labboy0276** [comment]
I will try tomm and see, I am gonna go outside today, it will be fun.

On Sun, Jan 31, 2016 at 1:36 PM, Mike Pirog <notifications@github.com>
wrote:

> In your Kalabox-CLI.yml make sure terminus also has links to the solr and
> redis services. Use the appserver definition in Kalabox-compose as a
> guide. Rebuild.
>
> Does that fix it?
>
> If so, submit a pr with the fix.
>
> On Sunday, January 31, 2016, John Ouellet <notifications@github.com>
> wrote:
>
> > correct
> >
> > On Sun, Jan 31, 2016 at 1:27 PM, Mike Pirog <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > I assume this only happens running drush and things are fine through
> the
> > ui
> > > on the appserver?
> > >
> > > On Sunday, January 31, 2016, John Ouellet <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
>
> > > wrote:
> > >
> > > > Hello!
> > > >
> > > > Created an app and tried to clear cache (all drush commands produce
> > this
> > > > result as well) and I get the error below:
> > > >
> > > > The app works in the browser,but it seems to think there is no redis
> > > > server? I made sure it was on PHP 5.3 for the site as I thought that
> > what
> > > > the error was, but it is all good on that front.
> > > >
> > > > Thoughts?
> > > >
> > > > john@kalamuna:~/kalabox/apps/prna/code$ kbox drush cc all
> > > > info: COMPOSE => 0=--project-name, 1=prna, 2=--file,
> > > 3=/home/john/kalabox/apps/prna/kalabox-compose.yml, 4=--file,
> > > 5=/home/john/kalabox/apps/prna/kalabox-cli.yml, 6=--file,
> > > 7=/home/john/kalabox/apps/prna/kalabox-cli.yml, 8=run, 9=--entrypoint,
> > > 10=bash --login -c, 11=--rm, 12=terminus, 13=drush8 cc all --strict=0,
> > > mode=attach
> > > > Starting prna_data_1
> > > > Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name
> or
> > > service not known PhpRedis.php:14 [warning]
> > > > Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name
> or
> > > service not known PhpRedis.php:14 [warning]
> > > > Drush command terminated abnormally due to an unrecoverable error.
> > > [error]
> > > > <h1>Additional uncaught exception thrown while handling
> > > exception.</h1><h2>Original</h2><p>RedisException: Redis server went
> away
> > > in Redis-&gt;auth() (line 18 of
> > >
> >
> /code/sites/all/modules/redis/lib/Redis/Client/PhpRedis.php).</p><h2>Additional</h2><p>RedisException:
> > > Redis server went away in Redis-&gt;auth() (line 18 of
> > > /code/sites/all/modules/redis/lib/Redis/Client/PhpRedis.php).</p><hr
> > > />info: DOCKER-COMPOSE => Run exited with code: 1
> > > > Unhandled rejection VError: code1err:more:
> > > > at ChildProcess.<anonymous>
> > (/usr/local/bin/lib/util/shell.js.jx:247:16)
> > > > at ChildProcess.emit (events.js:85:9)
> > > > at maybeClose (child_process.js:773:12)
> > > > at Process.ChildProcess._handle.onexit (child_process.js:839:1)
> > > > From previous event:
> > > > at Object.exports.spawn (/usr/local/bin/lib/util/shell.js.jx:211:10)
> > > > at Object.sh
> > >
> >
> (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/lib/bin.js.jx:92:20)
> > > > at
> > >
> >
> /usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:60:18
> > > > From previous event:
> > > > at shCompose
> > >
> >
> (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:42:6)
> > > > at Object.run
> > >
> >
> (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:343:12)
> > > > at /usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:260:24
> > > > at arrayMap (/usr/local/bin/node_modules/lodash/index.js.jx:1405:25)
> > > > at Function.map
> > (/usr/local/bin/node_modules/lodash/index.js.jx:6709:14)
> > > > at Object.run
> > > (/usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:177:26)
> > > > From previous event:
> > > > at /usr/local/bin/lib/engine.js.jx:471:29
> > > > From previous event:
> > > > at Object.exports.run (/usr/local/bin/lib/engine.js.jx:470:4)
> > > > at Object.task.func
> > > (/usr/local/bin/plugins/kalabox-cli/lib/tasks.js.jx:100:34)
> > > > at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:884:15)
> > > > at processTask (/usr/local/bin/bin/kbox.js.jx:168:16)
> > > > at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:231:12)
> > > > at process._tickCallback (node.js:803:1)
> > > > From previous event:
> > > > at main (/usr/local/bin/bin/kbox.js.jx:230:4)
> > > > at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:239:1)
> > > > at Module._compile (module.js:595:24)
> > > > at readX (module.js:1488:3)
> > > > at Object.Module._extensions..jx (module.js:1921:8)
> > > > at Module.load (module.js:416:30)
> > > > at Function.Module._load (module.js:380:8)
> > > > at Module.require (module.js:451:15)
> > > > at require (module.js:469:13)
> > > > at Object.<anonymous> (_jx_source:17:1)
> > > > at Module._compile (module.js:595:24)
> > > > at Module.load (module.js:425:6)
> > > > at Function.Module._load (module.js:380:8)
> > > > at Function.Module.runMain (module.js:813:8)
> > > > at startup (node.js:374:8)
> > > > at node.js:1461:1
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/kalabox/kalabox/issues/917>.
> > > >
> > >
> > >
> > > --
> > > Mike Pirog
> > > Co-Founder, Kalabox Inc
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/kalabox/kalabox/issues/917#issuecomment-177571227
> >.
> > >
> >
> >
> >
> > --
> > *John Ouellet*
> > *Sr Developer & Support Manager*
> > 415-470-3076
> > www.kalamuna.com
> >
> > Stay connected with Kalamuna on: Twitter
> > <
> >
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> > >
> > , Linkedin
> > <
> >
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> > >,
> > and Facebook
> > <
> >
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kalabox/kalabox/issues/917#issuecomment-177574329>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/917#issuecomment-177575389>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
@labboy0276 K, let me know. this should be a pretty easy fix so im going to assign it to you. Terminus service in `kalabox-cli.yml` should look like something like this. Note the "link" key 

```yml

#
# Pantheon tooling.
#
# This contains additional Pantheon specific tooling options such as
# drush, wp-cli and terminus.
#
terminus:

  # Comment this and uncomment 'build' below if you want to edit your
  # local dockerfile and build from there. This is useful for development
  image: kalabox/terminus:$KALABOX_PANTHEON_IMAGE_VERSION

  # Uncomment this and comment 'image' above if you want to edit your
  # local dockerfile and build from there. This is useful for development
  #
  # build: ./dockerfiles/terminus

  volumes:
    - $KALABOX_ENGINE_HOME:/user
    - $KALABOX_APP_ROOT:/src
    - $KALABOX_ENGINE_HOME/.kalabox/pantheon/session/$KALABOX_APP_PANTHEON_CONFIG_EMAIL:/root/.terminus/cache/session
    - $KALABOX_APP_ROOT/config/drush:/root/.drush
  volumes_from:
    - data
  environment:
    FRAMEWORK: $KALABOX_APP_PANTHEON_FRAMEWORK
    PHP_VERSION: 55
    DOMAIN: $KALABOX_DOMAIN
    TERM: xterm-color
    DOCROOT: $KALABOX_APP_PANTHEON_DOCROOT
    FILEMOUNT: $KALABOX_APP_PANTHEON_FILEMOUNT
    DRUPAL_HASH_SALT: $KALABOX_APP_PANTHEON_DRUPAL_HASH_SALT
    DB_HOST: $KALABOX_APP_PANTHEON_DB_HOST
    DB_PORT: $KALABOX_APP_PANTHEON_DB_PORT
    DB_USER: $KALABOX_APP_PANTHEON_DB_USER
    DB_PASSWORD: $KALABOX_APP_PANTHEON_DB_PASSWORD
    DB_NAME: $KALABOX_APP_PANTHEON_DB_NAME
    PANTHEON_ACCOUNT: $KALABOX_APP_PANTHEON_PANTHEON_ACCOUNT
    PANTHEON_SITE: $KALABOX_APP_PANTHEON_PANTHEON_SITE
    PANTHEON_SITE_NAME: $KALABOX_APP_PANTHEON_PANTHEON_SITE_NAME
    PANTHEON_ENVIRONMENT: $KALABOX_APP_PANTHEON_PANTHEON_ENVIRONMENT
    PANTHEON_INFRASTRUCTURE_ENVIRONMENT: $KALABOX_APP_PANTHEON_PANTHEON_INFRASTRUCTURE_ENVIRONMENT
    PRESSFLOW_SETTINGS: $KALABOX_APP_PANTHEON_PRESSFLOW_SETTINGS
    BACKDROP_SETTINGS: $KALABOX_APP_PANTHEON_PRESSFLOW_SETTINGS
    CACHE_HOST: $KALABOX_APP_PANTHEON_CACHE_HOST
    CACHE_PORT: $KALABOX_APP_PANTHEON_CACHE_PORT
    CACHE_PASSWORD: $KALABOX_APP_PANTHEON_CACHE_PASSWORD
    PANTHEON_INDEX_HOST: $KALABOX_APP_PANTHEON_PANTHEON_INDEX_HOST
    PANTHEON_INDEX_PORT: $KALABOX_APP_PANTHEON_PANTHEON_INDEX_PORT
    AUTH_KEY: $KALABOX_APP_PANTHEON_AUTH_KEY
    SECURE_AUTH_KEY: $KALABOX_APP_PANTHEON_SECURE_AUTH_KEY
    LOGGED_IN_KEY: $KALABOX_APP_PANTHEON_LOGGED_IN_KEY
    AUTH_SALT: $KALABOX_APP_PANTHEON_AUTH_SALT
    SECURE_AUTH_SALT: $KALABOX_APP_PANTHEON_SECURE_AUTH_SALT
    LOGGED_IN_SALT: $KALABOX_APP_PANTHEON_LOGGED_IN_SALT
    NONCE_SALT: $KALABOX_APP_PANTHEON_NONCE_SALT
  links:
    - db:database
    - redis:redis
    - solr:solr
  working_dir: /code
  stdin_open: true
  tty: true
```
