### ISSUE TITLE
Expose files directory for pantheon

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#922]
```yml
data:
  image: busybox
  volumes:
    - $KALABOX_APP_ROOT_BIND/files:/media:rw
    - /certs
    - /sql
    - /code
    - /backups
```

This seems to do the trick
